/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TableIdTypeImport } from './routes/$table.$id.$type'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TableIdTypeRoute = TableIdTypeImport.update({
  id: '/$table/$id/$type',
  path: '/$table/$id/$type',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$table/$id/$type': {
      id: '/$table/$id/$type'
      path: '/$table/$id/$type'
      fullPath: '/$table/$id/$type'
      preLoaderRoute: typeof TableIdTypeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$table/$id/$type': typeof TableIdTypeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$table/$id/$type': typeof TableIdTypeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$table/$id/$type': typeof TableIdTypeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$table/$id/$type'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$table/$id/$type'
  id: '__root__' | '/' | '/$table/$id/$type'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TableIdTypeRoute: typeof TableIdTypeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TableIdTypeRoute: TableIdTypeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$table/$id/$type"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$table/$id/$type": {
      "filePath": "$table.$id.$type.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
